Integrate other forks
visciang/nerves_dht pull request #57
Opened 2020-12-20 21:20 UTC by groma84

I consolidated other forks into one and successfully tested it on an Raspberry Pi 4

2020-12-20 22:03 UTC, visciang requested changes
Thank you for your contribution!
Could you address the points I've commented in the PR, please?

2020-12-20 22:03 UTC, visciang commented on mix.lock
> +  "elixir_make": {:hex, :elixir_make, "0.6.2", "7dffacd77dec4c37b39af867cedaabb0b59f6a871f89722c25b28fcd4bd70530", [:mix], [], "hexpm", "03e49eadda22526a7e5279d53321d1cced6552f344ba4e03e619063de75348
There are some old unused deps in the lock file.
"mix deps.clean --unlock --unused" will clean them

2020-12-21 07:58 UTC, groma84 commented on .gitignore
> +.vscode
I didn't even know there was a global gitignore file! Thanks for the info.

2020-12-21 07:58 UTC, groma84 commented on .gitignore
> +/priv
But there is a build artifact placed into the folder ("dht") - this has to be ignored at least.

2020-12-21 08:04 UTC, groma84 commented
Thanks for the feedback (and the awesome library)!
I pushed a new commit where I tried to integrate all requested changes. Please review again.

2020-12-22 08:35 UTC, visciang approved these changes

2020-12-22 08:35 UTC, merged